[tool.poetry]
name = "anjani_bot"
version = "1.1.2"
description = "Telegram group management bot"
license = "GPL-3.0-or-later"
authors = ["UserbotIndo Team"]
readme = "README.md"
homepage = "https://github.com/userbotindo/anjani#readme"
repository = "https://github.com/userbotindo/anjani"
documentation = "https://github.com/userbotindo/Anjani/wiki"
keywords = ["chatbot", "bot", "python", "telegram-bot", "pyrogram"]
classifiers = [
    "Environment :: Console",
    "Framework :: AsyncIO",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Communications",
    "Topic :: Communications :: Chat",
]

[tool.poetry.scripts]
anjani = "anjani_bot.main:start"

[tool.poetry.dependencies]
python = "^3.8"
PyYAML = "^5.4.1"
aiohttp = "^3.7.4"
aiorun = "^2020.12.1"
colorlog = "^5.0.1"
covid = "^2.4.1"
dnspython = "^2.1.0"
motor = "^2.4.0"
Pyrogram = "^1.2.9"
python-dotenv = "^0.17.1"
spamwatch = "^0.3.0"
TgCrypto = "^1.2.2"
uvloop = {version ="^0.15.2", optional = true}

[tool.poetry.dev-dependencies]
black = "^21.5b1"
pre-commit = "^2.12.1"
pylint = "^2.8.2"
mypy = "^0.812"

[tool.poetry.extras]
uvloop = ["uvloop"]

[tool.isort]
profile = "black"
known_third_party = ["aiohttp", "aiorun", "colorlog", "covid", "dotenv", "motor", "pymongo", "pyrogram", "spamwatch", "yaml"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
